### ISSUE TITLE
Plex Server Login Connection Refused 

### ISSUE THREAD

**Issue by bunnyUFO** [matthewdias/kitsu-plex-scrobbler#20]
After staring the scrobbler service when trying to log in to plex on the web app I get the following error:

```
scrobbler_1  | Error: connect ECONNREFUSED 172.17.0.1:32400
scrobbler_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
```

Not sure what is causing it. Could be a local configuration ion my plex server or netowrk.

Also, I'm running my plex server on windows. Not sure if that makes a difference.

**Comment by sachaw** [comment]
There was a Plex outage, this is likely what caused this.

**Comment by Wraithstalker90** [comment]
Im also having this problem on windows.
`Error: connect ECONNREFUSED 127.0.0.1:32400
scrobbler_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)`
